### ISSUE TITLE
Blacklist humanity-icon-theme

### ISSUE THREAD

**Issue by danirabbit** [elementary/seed-metapackages#13]
We don't use (not even for inheritance):
- [ ] Humanity
- [ ] Humanity-Dark
- [ ] Ubuntu-Mono-Dark
- [ ] Ubuntu-Mono-Light
- [ ] LoginIcons

**Comment by codygarver** [comment]
GTK package has a hard dependency on either humanity-*/ubuntu-mono OR adwaita-icon-theme-full. Choose one.

**Comment by danirabbit** [comment]
Adwaita would probably be a better choice considering Humanity is just a very very old recolor of elementary icons

**Comment by codygarver** [comment]
Done.
