### ISSUE TITLE
Tracking issue for Noble Packages

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/seed-metapackages#30]
Here's the difference between the current metapackage lists for Noble and the previous stable release we branched from:
https://github.com/elementary/metapackages/compare/7e2b3729463c3148fc8921b00bcb9115ba96cfa5..noble

As we get more of the packages built in the PPA and rebuild the metapackages, we should be able to reduce this diff. But this issue can serve as a reminder that there a bunch of packages currently not built/building for Noble.

**Comment by danirabbit** [comment]
It looks like we're still missing:

- [x] [Vala language server](https://code.launchpad.net/~elementary-os/+recipe/vala-language-server-daily)
- [x] [Vala lint](https://code.launchpad.net/~elementary-os/+recipe/vala-lint-daily)

**Comment by danirabbit** [comment]
This seems good so closing!
