### ISSUE TITLE
Add virtualization agents

### ISSUE THREAD

**Issue by mcatanzaro** [elementary/seed-metapackages#8]
Hi, I suggest adding common guest virtualization agents to the default install. This is to make elementary work better in VMs. Use case: I installed elementary in my GNOME Boxes VM, and resolution is poor, and the clipboard is not shared with my host so I can't copy/paste out of the VM. This is not a good user experience. I can fix it by installing the spice-vdagent package in elementary, but most users won't know how to do that.

In contrast, Fedora makes sure to install guest agents for all popular virtualization platforms by default. The Fedora package names are: hyperv-daemons, open-vm-tools-desktop (for VMWare), qemu-guest-agent, spice-vdagent (same as the elementary package), and virtualbox-guest-additions. Some or all of these would probably be good to have by default.

**Comment by codygarver** [comment]
`spice-vdagent` is a default package in all Ubuntu flavors now and we inherit it so it's present in elementary OS 5.0 Juno.
